version: "3.7"

services:
  phoenix:
    image: registry.gitlab.com/newnixio/newnix:latest
    networks:
      - newnix_prod
      - traefik_public
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.newnix-app.service=newnix-app"
        - "traefik.http.routers.newnix-app.entrypoints=websecure"
        - "traefik.http.routers.newnix-app.rule=Host(`app.newnix.io`)"
        - "traefik.http.routers.newnix-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.newnix-app.loadbalancer.server.port=4000"
    restart: always
    depends_on:
      - pg_prod

  pg_prod:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: newnix_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - newnix_prod


volumes:
  pgdata_prod:
    external: true

networks:
  traefik_public:
    external: true
  newnix_prod:
    external: true